In [ ]:
from pandas import read_csv
from datetime import datetime
from google.colab import files
import io
import pandas as pd
from pandas import read_csv
from matplotlib import pyplot as plt
from pandas import read_csv
from pandas import DataFrame
from pandas import concat
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import mean_squared_error
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
import numpy as np
import plotly.graph_objects as go

In [ ]:
# load data
 
uploaded = files.upload()

Saving BOVA11.SA.csv to BOVA11.SA.csv


In [ ]:
BOVA11 = read_csv(io.BytesIO(uploaded['BOVA11.SA.csv']))

# mark all NA values with 0
# summarize first 5 rows
print(BOVA11.head(5))
print(len(BOVA11))

         Date       Open       High        Low      Close  Adj Close     Volume
0  2019-01-02  84.599998  88.260002  84.349998  87.900002  87.900002  5021260.0
1  2019-01-03  87.550003  88.400002  86.800003  88.000000  88.000000  4300220.0
2  2019-01-04  88.199997  89.449997  87.629997  88.500000  88.500000  2449750.0
3  2019-01-07  88.650002  89.320000  88.059998  88.480003  88.480003  2891360.0
4  2019-01-08  88.750000  88.970001  87.870003  88.830002  88.830002  3441770.0
371


In [ ]:
Train = BOVA11[:int(0.7*len(BOVA11))].copy()
Test = BOVA11[int(0.7*len(BOVA11)):].copy()

In [ ]:
#Prices Plot IBOVA11
from google.colab import files
plt.figure(figsize = (18,9),dpi=1000)
plt.plot(BOVA11["Open"])
plt.plot(BOVA11["High"])
plt.plot(BOVA11["Low"])
plt.plot(BOVA11["Close"])
# plt.plot(Train["Close"],'black')
# plt.plot(Test["Close"],'black')
# plt.axvline(x=int(0.7*len(BOVA11)))
plt.xticks(range(0,BOVA11.shape[0],50),BOVA11['Date'].loc[::50],rotation=45, fontsize=18)
plt.yticks(fontsize=18)
plt.title('BOVA11', fontsize=18)
plt.ylabel('Price (R$)', fontsize=18)
plt.xlabel('Days', fontsize=17)
plt.legend(['Open','High','Low','Close'], loc='upper left')
plt.savefig("img11.pdf")
files.download("img11.pdf") 
plt.show()


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<Figure size 432x288 with 0 Axes>

In [ ]:
# fig = go.Figure(data=[go.Candlestick(x=dataset.index,
#                 open=dataset['Open'],
#                 high=dataset['High'],
#                 low=dataset['Low'],
#                 close=dataset['Close'])])

# fig.show()

In [ ]:
#Normalization

BOVA11['LOG_RETURN'] = np.log(BOVA11['Close']).diff()
BOVA11.fillna(0, inplace=True)
BOVA11.head()

Date       Open       High  ...  Adj Close     Volume  LOG_RETURN
0  2019-01-02  84.599998  88.260002  ...  87.900002  5021260.0    0.000000
1  2019-01-03  87.550003  88.400002  ...  88.000000  4300220.0    0.001137
2  2019-01-04  88.199997  89.449997  ...  88.500000  2449750.0    0.005666
3  2019-01-07  88.650002  89.320000  ...  88.480003  2891360.0   -0.000226
4  2019-01-08  88.750000  88.970001  ...  88.830002  3441770.0    0.003948

[5 rows x 8 columns]

In [ ]:
#Plot Log Retorno:

plt.figure(figsize = (18,9),dpi=1000)
plt.plot(BOVA11["LOG_RETURN"])
plt.xticks(range(0,BOVA11.shape[0],50),BOVA11['Date'].loc[::50],rotation=45, fontsize=18)
plt.title('BOVA11', fontsize=18)
plt.ylabel('Log-Retorno', fontsize=18)
plt.xlabel('Days', fontsize=18)
plt.savefig("img13.pdf")
files.download("img13.pdf")
plt.show()

In [ ]:
y = []
for i in np.array(BOVA11['LOG_RETURN']):
  if i < 0:
    y.append(0)
  else:
    y.append(1)

print(y)

[1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 

In [ ]:
# Put your inputs into a single list
input_cols = ['Close','Volume','LOG_RETURN']
BOVA11['single_input_vector'] = BOVA11[input_cols].apply(tuple, axis=1).apply(list)
BOVA11

Date  ...                                single_input_vector
0    2019-01-02  ...                        [87.900002, 5021260.0, 0.0]
1    2019-01-03  ...           [88.0, 4300220.0, 0.0011369870339468235]
2    2019-01-04  ...            [88.5, 2449750.0, 0.005665737535676563]
3    2019-01-07  ...    [88.480003, 2891360.0, -0.00022598033389176209]
4    2019-01-08  ...  [88.83000200000001, 3441770.0, 0.0039478816165...
..          ...  ...                                                ...
366  2020-06-24  ...       [90.769997, 9841040.0, -0.01628189831957272]
367  2020-06-25  ...       [92.389999, 8739510.0, 0.017689935371003607]
368  2020-06-26  ...      [90.220001, 7314530.0, -0.023767593794705277]
369  2020-06-29  ...        [91.849998, 8447360.0, 0.01790564682223561]
370  2020-06-30  ...      [92.010002, 7447350.0, 0.0017404986445352932]

[371 rows x 9 columns]

In [ ]:
# Double-encapsulate list so that you can sum it in the next step and keep time steps as separate elements
BOVA11['single_input_vector'] = BOVA11.single_input_vector.apply(lambda x: [list(x)])
BOVA11

Date  ...                                single_input_vector
0    2019-01-02  ...                      [[87.900002, 5021260.0, 0.0]]
1    2019-01-03  ...         [[88.0, 4300220.0, 0.0011369870339468235]]
2    2019-01-04  ...          [[88.5, 2449750.0, 0.005665737535676563]]
3    2019-01-07  ...  [[88.480003, 2891360.0, -0.00022598033389176209]]
4    2019-01-08  ...  [[88.83000200000001, 3441770.0, 0.003947881616...
..          ...  ...                                                ...
366  2020-06-24  ...     [[90.769997, 9841040.0, -0.01628189831957272]]
367  2020-06-25  ...     [[92.389999, 8739510.0, 0.017689935371003607]]
368  2020-06-26  ...    [[90.220001, 7314530.0, -0.023767593794705277]]
369  2020-06-29  ...      [[91.849998, 8447360.0, 0.01790564682223561]]
370  2020-06-30  ...    [[92.010002, 7447350.0, 0.0017404986445352932]]

[371 rows x 9 columns]

In [ ]:
# Use .cumsum() to include previous row vectors in the current row list of vectors
BOVA11['cumulative_input_vectors'] = BOVA11.single_input_vector.cumsum()
BOVA11['Output'] = y
BOVA11

Date  ...  Output
0    2019-01-02  ...       1
1    2019-01-03  ...       1
2    2019-01-04  ...       1
3    2019-01-07  ...       0
4    2019-01-08  ...       1
..          ...  ...     ...
366  2020-06-24  ...       0
367  2020-06-25  ...       1
368  2020-06-26  ...       0
369  2020-06-29  ...       1
370  2020-06-30  ...       1

[371 rows x 11 columns]

In [ ]:
output_cols = ['Output']
BOVA11['output_vector'] = BOVA11[output_cols].apply(tuple, axis=1).apply(list)
BOVA11

Date       Open  ...  Output  output_vector
0    2019-01-02  84.599998  ...       1            [1]
1    2019-01-03  87.550003  ...       1            [1]
2    2019-01-04  88.199997  ...       1            [1]
3    2019-01-07  88.650002  ...       0            [0]
4    2019-01-08  88.750000  ...       1            [1]
..          ...        ...  ...     ...            ...
366  2020-06-24  92.050003  ...       0            [0]
367  2020-06-25  90.790001  ...       1            [1]
368  2020-06-26  91.870003  ...       0            [0]
369  2020-06-29  91.150002  ...       1            [1]
370  2020-06-30  91.779999  ...       1            [1]

[371 rows x 12 columns]

In [ ]:
# Pad your sequences so they are the same length
from keras.preprocessing.sequence import pad_sequences

max_sequence_length = BOVA11.cumulative_input_vectors.apply(len).max()
# Save it as a list   
padded_sequences = pad_sequences(BOVA11.cumulative_input_vectors.tolist(), max_sequence_length).tolist()
BOVA11['padded_input_vectors'] = pd.Series(padded_sequences).apply(np.asarray)

In [ ]:
BOVA11

Date  ...                               padded_input_vectors
0    2019-01-02  ...  [[0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [...
1    2019-01-03  ...  [[0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [...
2    2019-01-04  ...  [[0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [...
3    2019-01-07  ...  [[0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [...
4    2019-01-08  ...  [[0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [...
..          ...  ...                                                ...
366  2020-06-24  ...  [[0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [...
367  2020-06-25  ...  [[0, 0, 0], [0, 0, 0], [0, 0, 0], [87, 5021260...
368  2020-06-26  ...  [[0, 0, 0], [0, 0, 0], [87, 5021260, 0], [88, ...
369  2020-06-29  ...  [[0, 0, 0], [87, 5021260, 0], [88, 4300220, 0]...
370  2020-06-30  ...  [[87, 5021260, 0], [88, 4300220, 0], [88, 2449...

[371 rows x 13 columns]

In [ ]:
# Extract your training data
X_train_init = np.asarray(BOVA11.padded_input_vectors)
# Use hstack to and reshape to make the inputs a 3d vector
X_train = np.hstack(X_train_init).reshape(len(BOVA11),max_sequence_length,len(input_cols))
y_train = np.hstack(np.asarray(BOVA11.Output)).reshape(len(BOVA11),len(output_cols))

In [ ]:
print(X_train_init)
print(X_train.shape)

[array([[      0,       0,       0],
       [      0,       0,       0],
       [      0,       0,       0],
       ...,
       [      0,       0,       0],
       [      0,       0,       0],
       [     87, 5021260,       0]])
 array([[      0,       0,       0],
       [      0,       0,       0],
       [      0,       0,       0],
       ...,
       [      0,       0,       0],
       [     87, 5021260,       0],
       [     88, 4300220,       0]])
 array([[      0,       0,       0],
       [      0,       0,       0],
       [      0,       0,       0],
       ...,
       [     87, 5021260,       0],
       [     88, 4300220,       0],
       [     88, 2449750,       0]])
 array([[      0,       0,       0],
       [      0,       0,       0],
       [      0,       0,       0],
       ...,
       [     88, 4300220,       0],
       [     88, 2449750,       0],
       [     88, 2891360,       0]])
 array([[      0,       0,       0],
       [      0,       0,       0],
       

In [ ]:
# Get your input dimensions
# Input length is the length for one input sequence (i.e. the number of rows for your sample)
# Input dim is the number of dimensions in one input vector (i.e. number of input columns)
input_length = X_train.shape[1]
input_dim = X_train.shape[2]
# Output dimensions is the shape of a single output vector
# In this case it's just 1, but it could be more
output_dim = len(y_train[0])

In [ ]:
from keras.models import Model, Sequential
from keras.layers import LSTM, Dense

# Build the model
model = Sequential()

# I arbitrarily picked the output dimensions as 4
model.add(LSTM(4, input_dim = input_dim, input_length = input_length))
# The max output value is > 1 so relu is used as final activation.
model.add(Dense(output_dim, activation='relu'))

model.compile(loss='mean_squared_error',
              optimizer='sgd',
              metrics=['accuracy'])

In [ ]:
# Set batch_size to 7 to show that it doesn't have to be a factor or multiple of your sample size
history = model.fit(X_train, y_train,
              batch_size=7, epochs=3,
              verbose = 1)

Epoch 1/3
53/53 [==============================] - 3s 62ms/step - loss: 0.3075 - accuracy: 0.4636
Epoch 2/3
53/53 [==============================] - 3s 49ms/step - loss: 0.2593 - accuracy: 0.5121
Epoch 3/3
53/53 [==============================] - 3s 51ms/step - loss: 0.2557 - accuracy: 0.5121


In [ ]:
X = X_train
model.predict(X)

array([[0.46141258],
       [0.46141258],
       [0.46141258],
       [0.46141258],
       [0.46141258],
       [0.46141258],
       [0.46141258],
       [0.46141258],
       [0.46141258],
       [0.46141258],
       [0.46141258],
       [0.46141258],
       [0.46141258],
       [0.46141258],
       [0.46141258],
       [0.46141258],
       [0.46141258],
       [0.46141258],
       [0.46141258],
       [0.46141258],
       [0.46141258],
       [0.46141258],
       [0.46141258],
       [0.46141258],
       [0.46141258],
       [0.46141258],
       [0.46141258],
       [0.46141258],
       [0.46141258],
       [0.46141258],
       [0.46141258],
       [0.46141258],
       [0.46141258],
       [0.46141258],
       [0.46141258],
       [0.46141258],
       [0.46141258],
       [0.46141258],
       [0.46141258],
       [0.46141258],
       [0.46141258],
       [0.46141258],
       [0.44529036],
       [0.46855074],
       [0.46855074],
       [0.46855074],
       [0.46855074],
       [0.468

In [ ]:
print(y_train)

[[1]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
